### ISSUE TITLE
Frontend Checklist

### ISSUE THREAD

**Issue by mcmahoniel** [RailsStudyGroup/stationstream#5]
~~\- [ ] Left-side layout~~
- [x] Right-side column for video feed
- [x] Update GitHub link to indicate we're leaving the page
  - [x] Optional: Pop up instead of direct link
- [x] Add Active class to current route
- [x] Add Favicon
- [x] Add avatars to About page
- [x] Link to Github, Space Apps Challenge on About page
- [x] Add content to Home page
- [x] Update Github readme
